CSharpMVC/SlnExercicioBobsBurguerMVC/Devs2Blu.Exercicio2CsharpMVC/Models/BobsBurguer.cs
namespace Devs2Blu.Exercicio2CsharpMVC.Models
{
    public class BobsBurguer
    {
        public int id { get; set; }

        public string name { get; set; }

        public string image { get; set; }

        public string occupation { get; set; }

        public string url{ get; set; }

        public string wikiUrl { get; set; }
    }
}

CSharpMVC/SlnExercicioBobsBurguerMVC/Devs2Blu.Exercicio2CsharpMVC/Models/Burguer.cs
namespace Devs2Blu.Exercicio2CsharpMVC.Models
{
    public class Burguer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
    }
}

CSharpMVC/SlnExercicioBobsBurguerMVC/Devs2Blu.Exercicio2CsharpMVC/Models/ErrorViewModel.cs
namespace Devs2Blu.Exercicio2CsharpMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSharpMVC/SlnExercicioBobsBurguerMVC/Devs2Blu.Exercicio2CsharpMVC/Controllers/BobsBurguerController.cs
using Devs2Blu.Exercicio2CsharpMVC.Models;
using Devs2Blu.Exercicio2CsharpMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace Devs2Blu.Exercicio2CsharpMVC.Controllers
{
    [Route("personagens")]
    public class BobsBurguerController : Controller
    {
        private readonly ServiceApi _serviceApi;

        public BobsBurguerController()
        {
            _serviceApi = new ServiceApi();
        }
                
        public async Task<IActionResult> Index()
        {
            var personagens = await _serviceApi.GetCharacters();
            return View(personagens);
        }

        [Route("burguers")]
        public async Task<IActionResult> Burguers()
        {
            var burguers = await _serviceApi.GetBurguers();
            return View(burguers);
        }

        [Route("burguerdodia")]
        public async Task<PartialViewResult> BurguerdoDia()
        {
            var burguer = await _serviceApi.GetBurguerOfTheDay();
            return PartialView(burguer);
        }

        [Route("search/{name}")]
        public async Task<IActionResult> SearchCharacter(string name)
        {
            var character = await _serviceApi.GetCharacterByName(name);
            return PartialView(character);
        }
    }
}

CSharpMVC/SlnExercicioBobsBurguerMVC/Devs2Blu.Exercicio2CsharpMVC/Controllers/HomeController.cs
using Devs2Blu.Exercicio2CsharpMVC.Models;
using Devs2Blu.Exercicio2CsharpMVC.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Devs2Blu.Exercicio2CsharpMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ServiceApi _serviceApi;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            _serviceApi = new ServiceApi();
        }

        public IActionResult Index()
        {
            return View();
        }
                
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSharpMVC/SlnExercicioBobsBurguerMVC/Devs2Blu.Exercicio2CsharpMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Devs2Blu.Exercicio2CsharpMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Devs2Blu.Exercicio2CsharpMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Devs2Blu.Exercicio2CsharpMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="BobsBurguer" asp-action="Index">Personagens</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="BobsBurguer" asp-action="Burguers">Hamburguers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Contato</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input id="input-search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button id="btn-search" class="btn btn-outline-success" type="submit">Buscar</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            &copy; 2022 - Devs2Blu.Exercicio2CsharpMVC - <a id="footer-contato" asp-area="" asp-controller="Home" asp-action="Privacy">Contato</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>